"""
trading.py
Trading-related constants for Binance Terminal.
"""

# ===== DATA STRUCTURE KEYS =====

# JSON Configuration Keys
COINS_KEY = "coins"
DYNAMIC_COIN_KEY = "dynamic_coin"
VALUES_KEY = "values"
CURRENT_PRICE_KEY = "current"
PREVIOUS_PRICE_KEY = "15_min_ago"

# Portfolio Keys
PORTFOLIO_KEY = "portfolio"
ASSETS_KEY = "assets"
TOTAL_VALUE_KEY = "total_value_usdt"
TIMESTAMP_KEY = "timestamp"

# Trade Data Keys
TRADE_SYMBOL_KEY = "symbol"
TRADE_SIDE_KEY = "side"
TRADE_TYPE_KEY = "type"
TRADE_QUANTITY_KEY = "quantity"
TRADE_PRICE_KEY = "price"
TRADE_TOTAL_COST_KEY = "total_cost"
TRADE_ORDER_ID_KEY = "order_id"

# ===== TRADING CONFIGURATION =====

# Trading Indices
FAVORITE_COIN_COUNT = 5
DYNAMIC_COIN_INDEX = -1  # Special index for dynamic coin
MAX_FAVORITE_COINS = 5

# Order Types
ORDER_TYPE_MARKET = "MARKET"
ORDER_TYPE_LIMIT = "LIMIT"
DEFAULT_ORDER_TYPE = ORDER_TYPE_MARKET

# Trading Defaults
DEFAULT_BUY_PERCENTAGE = 10.0  # 10% of wallet
DEFAULT_SELL_PERCENTAGE = 25.0  # 25% of asset
MIN_TRADE_PERCENTAGE = 1.0
MAX_TRADE_PERCENTAGE = 100.0

# Risk Management
DEFAULT_STOP_LOSS_PERCENTAGE = 5.0  # 5% stop loss
DEFAULT_TAKE_PROFIT_PERCENTAGE = 15.0  # 15% take profit
MAX_POSITION_SIZE_PERCENTAGE = 20.0  # Max 20% of portfolio per coin

# Trading Amounts
MIN_USDT_TRADE_AMOUNT = 10.0  # Minimum $10 trade
DEFAULT_TRADE_AMOUNT = 50.0  # Default $50 trade
MAX_TRADE_AMOUNT = 10000.0  # Maximum $10,000 trade

# ===== TRADING TYPES =====

# Buy Types
BUY_TYPE_5_PERCENT = "5%_Buy"
BUY_TYPE_10_PERCENT = "10%_Buy"
BUY_TYPE_25_PERCENT = "25%_Buy"
BUY_TYPE_SOFT = "Soft_Buy"
BUY_TYPE_CUSTOM = "Custom_Buy"

# Sell Types
SELL_TYPE_25_PERCENT = "25%_Sell"
SELL_TYPE_40_PERCENT = "40%_Sell"
SELL_TYPE_50_PERCENT = "50%_Sell"
SELL_TYPE_ALL = "All_Sell"
SELL_TYPE_SOFT = "Soft_Sell"
SELL_TYPE_CUSTOM = "Custom_Sell"

# Trade Categories
TRADE_CATEGORY_BUY = "BUY"
TRADE_CATEGORY_SELL = "SELL"
TRADE_CATEGORY_TRANSFER = "TRANSFER"

# ===== DISPLAY CONFIGURATION =====

# Price Display
PRICE_DECIMAL_PLACES = 2
PERCENTAGE_DECIMAL_PLACES = 2
QUANTITY_DECIMAL_PLACES = 6

# Color Coding
POSITIVE_COLOR = "#00FF00"  # Green
NEGATIVE_COLOR = "#FF0000"  # Red
NEUTRAL_COLOR = "#FFFF00"  # Yellow
WARNING_COLOR = "#FFA500"  # Orange

# Table Configuration
DEFAULT_TABLE_ROWS = 10
MAX_TABLE_ROWS = 100

# ===== VALIDATION RULES =====

# Symbol Validation
MIN_SYMBOL_LENGTH = 5  # e.g., "BTCUSDT" = 7 chars
MAX_SYMBOL_LENGTH = 20
REQUIRED_SYMBOL_SUFFIX = "USDT"

# Quantity Validation
MIN_QUANTITY = 0.000001
MAX_QUANTITY = 1000000.0

# Price Validation
MIN_PRICE = 0.000001
MAX_PRICE = 10000000.0

__all__ = [
    # Data structure keys
    "COINS_KEY",
    "DYNAMIC_COIN_KEY",
    "VALUES_KEY",
    "CURRENT_PRICE_KEY",
    "PREVIOUS_PRICE_KEY",
    "PORTFOLIO_KEY",
    "ASSETS_KEY",
    "TOTAL_VALUE_KEY",
    "TIMESTAMP_KEY",
    "TRADE_SYMBOL_KEY",
    "TRADE_SIDE_KEY",
    "TRADE_TYPE_KEY",
    "TRADE_QUANTITY_KEY",
    "TRADE_PRICE_KEY",
    "TRADE_TOTAL_COST_KEY",
    "TRADE_ORDER_ID_KEY",
    # Trading configuration
    "FAVORITE_COIN_COUNT",
    "DYNAMIC_COIN_INDEX",
    "MAX_FAVORITE_COINS",
    "ORDER_TYPE_MARKET",
    "ORDER_TYPE_LIMIT",
    "DEFAULT_ORDER_TYPE",
    "DEFAULT_BUY_PERCENTAGE",
    "DEFAULT_SELL_PERCENTAGE",
    "MIN_TRADE_PERCENTAGE",
    "MAX_TRADE_PERCENTAGE",
    "DEFAULT_STOP_LOSS_PERCENTAGE",
    "DEFAULT_TAKE_PROFIT_PERCENTAGE",
    "MAX_POSITION_SIZE_PERCENTAGE",
    "MIN_USDT_TRADE_AMOUNT",
    "DEFAULT_TRADE_AMOUNT",
    "MAX_TRADE_AMOUNT",
    # Trading types
    "BUY_TYPE_5_PERCENT",
    "BUY_TYPE_10_PERCENT",
    "BUY_TYPE_25_PERCENT",
    "BUY_TYPE_SOFT",
    "BUY_TYPE_CUSTOM",
    "SELL_TYPE_25_PERCENT",
    "SELL_TYPE_40_PERCENT",
    "SELL_TYPE_50_PERCENT",
    "SELL_TYPE_ALL",
    "SELL_TYPE_SOFT",
    "SELL_TYPE_CUSTOM",
    "TRADE_CATEGORY_BUY",
    "TRADE_CATEGORY_SELL",
    "TRADE_CATEGORY_TRANSFER",
    # Display configuration
    "PRICE_DECIMAL_PLACES",
    "PERCENTAGE_DECIMAL_PLACES",
    "QUANTITY_DECIMAL_PLACES",
    "POSITIVE_COLOR",
    "NEGATIVE_COLOR",
    "NEUTRAL_COLOR",
    "WARNING_COLOR",
    "DEFAULT_TABLE_ROWS",
    "MAX_TABLE_ROWS",
    # Validation rules
    "MIN_SYMBOL_LENGTH",
    "MAX_SYMBOL_LENGTH",
    "REQUIRED_SYMBOL_SUFFIX",
    "MIN_QUANTITY",
    "MAX_QUANTITY",
    "MIN_PRICE",
    "MAX_PRICE",
]
